include:
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
  - board: corneish_zen_v1_left
  - board: corneish_zen_v1_right
  # snippet: zmk-usb-logging # uncomment to enable logging